# Array

In [1]:
#Array stores homogeneous data
#array stores data in higher dimension
#array are fater than list
#array allows all mathematical operation
#consume less memory

In [41]:
import numpy as np

In [3]:
print(np.__version__)

1.21.5


In [4]:
ar1=np.array([1,2,3,3])#np.array()
ar1

array([1, 2, 3, 3])

In [5]:
type(ar1)

numpy.ndarray

In [6]:
ar2=np.array((1,2,3,3))
print(ar2)
print(type(ar2))

[1 2 3 3]
<class 'numpy.ndarray'>


In [7]:
ar2=np.array({1,2,3,3})
print(ar2)
print(type(ar2))

{1, 2, 3}
<class 'numpy.ndarray'>


In [8]:
#Dimensions of array
#0-D
arr1=np.array(30)
print(arr1)

30


In [9]:
arr1.ndim#dimension

0

In [10]:
#1-D
arr2=np.array([11,22,33])
arr2

array([11, 22, 33])

In [11]:
arr2.ndim

1

In [12]:
#2-D
arr3=np.array([[10,20,30],[40,50,60]])
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
arr3.ndim

2

In [30]:
#3-D
arr4=np.array([[[11,22,33],[44,55,66]],[[10,20,30],[40,50,60]]])
arr4

array([[[11, 22, 33],
        [44, 55, 66]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [15]:
arr4.ndim

1

In [16]:
arr5=np.array([1,2,3,4],ndmin=5)
arr5

array([[[[[1, 2, 3, 4]]]]])

In [17]:
arr5.ndim

5

In [18]:
arr6=np.array([1,2,3,4],ndmin=10)
arr6

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [19]:
arr6.ndim

10

In [20]:
#Indexing
arr2

array([11, 22, 33])

In [21]:
arr2[1]

22

In [22]:
print(arr2[0]+arr2[1])

33


In [23]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
arr3[1,0]

40

In [25]:
arr3[1,2]

60

In [26]:
arr3[0,1]

20

In [27]:
arr3[1,1]

50

In [32]:
arr4

array([[[11, 22, 33],
        [44, 55, 66]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [33]:
arr4[1,1,1]

50

In [35]:
arr4[0,1,1]

55

In [37]:
arr4[0,1,1]

55

In [38]:
arr4[1,1,2]

60

In [29]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
a[1,-1]

10

In [43]:
#slicing of array
ar1=np.array([1,2,4,6,3,7,8,90])
ar1

array([ 1,  2,  4,  6,  3,  7,  8, 90])

In [44]:
ar1[2:6]

array([4, 6, 3, 7])

In [45]:
ar1[:4]

array([1, 2, 4, 6])

In [46]:
ar1[:]

array([ 1,  2,  4,  6,  3,  7,  8, 90])

In [47]:
ar1[-4:-1]

array([3, 7, 8])

In [49]:
ar1[-7:-4]

array([2, 4, 6])

In [50]:
ar1[::2]

array([1, 4, 3, 8])

In [53]:
ar1[2::3]

array([4, 7])

In [54]:
ar1[2:7:2]

array([4, 3, 8])

In [56]:
#slicing of 2-D
ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
ar2[1,1:4]

array([7, 8, 9])

In [68]:
ar2[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [58]:
ar2[0,2:]

array([3, 4, 5])

In [64]:
ar2[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [65]:
ar2[0:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [66]:
ar2[0:2,1:3]

array([[2, 3],
       [7, 8]])