# Array

In [1]:
#Array stores homogeneous data
#array stores data in higher dimension
#array are fater than list
#array allows all mathematical operation
#consume less memory

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.21.5


In [4]:
ar1=np.array([1,2,3,3])#np.array()
ar1

array([1, 2, 3, 3])

In [5]:
type(ar1)

numpy.ndarray

In [6]:
ar2=np.array((1,2,3,3))
print(ar2)
print(type(ar2))

[1 2 3 3]
<class 'numpy.ndarray'>


In [7]:
ar2=np.array({1,2,3,3})
print(ar2)
print(type(ar2))

{1, 2, 3}
<class 'numpy.ndarray'>


In [8]:
#Dimensions of array
#0-D
arr1=np.array(30)
print(arr1)

30


In [9]:
arr1.ndim#dimension

0

In [10]:
#1-D
arr2=np.array([11,22,33])
arr2

array([11, 22, 33])

In [11]:
arr2.ndim

1

In [12]:
#2-D
arr3=np.array([[10,20,30],[40,50,60]])
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
arr3.ndim

2

In [14]:
#3-D
arr4=np.array([[[11,22,33],[44,55,66]],[[10,20,30],[40,50,60]]])
arr4

array([[[11, 22, 33],
        [44, 55, 66]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [15]:
arr4.ndim

3

In [16]:
arr5=np.array([1,2,3,4],ndmin=5)
arr5

array([[[[[1, 2, 3, 4]]]]])

In [17]:
arr5.ndim

5

In [18]:
arr6=np.array([1,2,3,4],ndmin=10)
arr6

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [19]:
arr6.ndim

10

In [20]:
#Indexing
arr2

array([11, 22, 33])

In [21]:
arr2[1]

22

In [22]:
print(arr2[0]+arr2[1])

33


In [23]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
arr3[1,0]

40

In [25]:
arr3[1,2]

60

In [26]:
arr3[0,1]

20

In [27]:
arr3[1,1]

50

In [28]:
arr4

array([[[11, 22, 33],
        [44, 55, 66]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [29]:
arr4[1,1,1]

50

In [30]:
arr4[0,1,1]

55

In [31]:
arr4[0,1,1]

55

In [32]:
arr4[1,1,2]

60

In [33]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
a[1,-1]

10

In [35]:
#slicing of array
ar1=np.array([1,2,4,6,3,7,8,90])
ar1

array([ 1,  2,  4,  6,  3,  7,  8, 90])

In [36]:
ar1[2:6]

array([4, 6, 3, 7])

In [37]:
ar1[:4]

array([1, 2, 4, 6])

In [38]:
ar1[:]

array([ 1,  2,  4,  6,  3,  7,  8, 90])

In [39]:
ar1[-4:-1]

array([3, 7, 8])

In [40]:
ar1[-7:-4]

array([2, 4, 6])

In [41]:
ar1[::2]

array([1, 4, 3, 8])

In [42]:
ar1[2::3]

array([4, 7])

In [43]:
ar1[2:7:2]

array([4, 3, 8])

In [44]:
#slicing of 2-D
ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
ar2[1,1:4]

array([7, 8, 9])

In [46]:
ar2[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [47]:
ar2[0,2:]

array([3, 4, 5])

In [48]:
ar2[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [49]:
ar2[0:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [50]:
ar2[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [51]:
n1=np.array([[[10,20,30],[40,50,60]],[[800,400,500],[23,45,89]]])
n1
#[plane,row,col]

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[800, 400, 500],
        [ 23,  45,  89]]])

In [52]:
n1.ndim

3

In [53]:
# Question for o/p 50,60,400,500
n1[(0,1), (1,0), 1:]

array([[ 50,  60],
       [400, 500]])

In [54]:
n1[(0,1),(1,0),:2]

array([[ 40,  50],
       [800, 400]])

In [55]:
n1[(0,1),(0,1),:2]

array([[10, 20],
       [23, 45]])

In [56]:
n1[1,0:2,1:]

array([[400, 500],
       [ 45,  89]])

In [57]:
n1[1,0:2,:2]

array([[800, 400],
       [ 23,  45]])

In [58]:
n1[1,0:1,:3]

array([[800, 400, 500]])

In [59]:
n1[1,0:2,1:3]

array([[400, 500],
       [ 45,  89]])

In [60]:
n1[0,0:2,:2]

array([[10, 20],
       [40, 50]])

In [61]:
n1[1,0,1]

400

In [62]:
n1[1,1,1]

45

In [63]:
n1[0,0,2]

30

In [64]:
n1[1,1,0]

23

In [65]:
n1[0,0:,1:]

array([[20, 30],
       [50, 60]])

In [66]:
#Data types in array
#array support string(S),int(i),float(f),boolean(b),complex-float(c),
#U-unicode string, date time(M),timedelta(m)

In [67]:
b1=np.array([1,2,3])
b1

array([1, 2, 3])

In [68]:
b1.dtype

dtype('int32')

In [69]:
b2=np.array(["apple","banana","cherry"])
b2

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [70]:
b2.dtype

dtype('<U6')

In [71]:
#Create array with dtype
b3=np.array([1,2,3],dtype="S")
b3

array([b'1', b'2', b'3'], dtype='|S1')

In [72]:
b4=np.array([1,2,3],dtype="i4")
b4

array([1, 2, 3])

In [73]:
b4.dtype

dtype('int32')

In [74]:
b5=np.array(["abc",3,4],dtype="S")
b5

array([b'abc', b'3', b'4'], dtype='|S3')

In [75]:
b6=np.array([1,2,3,4])

In [76]:
b6.astype('i')

array([1, 2, 3, 4], dtype=int32)

In [77]:
#copy()
x1=np.array([1,2,34])
x1

array([ 1,  2, 34])

In [78]:
x2=x1.copy()
x2

array([ 1,  2, 34])

In [79]:
x1[2]

34

In [80]:
x1[2]=500
x1

array([  1,   2, 500])

In [81]:
x2

array([ 1,  2, 34])

In [82]:
#view()
c1=np.array([3,4,5,8])
c1

array([3, 4, 5, 8])

In [83]:
c2=c1.view()
c2

array([3, 4, 5, 8])

In [84]:
c1[1]

4

In [85]:
c1[1]=40
c1

array([ 3, 40,  5,  8])

In [86]:
c2

array([ 3, 40,  5,  8])

In [87]:
#shape of array
c1.shape

(4,)

In [88]:
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [89]:
ar2.ndim

2

In [90]:
ar2.shape

(2, 5)

In [91]:
n1

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[800, 400, 500],
        [ 23,  45,  89]]])

In [92]:
n1.ndim

3

In [93]:
n1.shape

(2, 2, 3)

In [94]:
v=np.array([1,2,3])
v.ndim

1

In [95]:
v.shape

(3,)

In [96]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
a1.shape

(2, 4)

In [98]:
a1.ndim

2

In [99]:
a2=np.array([1,2,3,4],ndmin=5)
a2

array([[[[[1, 2, 3, 4]]]]])

In [100]:
a2.shape

(1, 1, 1, 1, 4)

# Reshaping of array

In [101]:
#1D to 2D
ar1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
ar1.shape

(12,)

In [103]:
ar1.ndim

1

In [104]:
ar_n1=ar1.reshape(4,3)
ar_n1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [105]:
ar_n1.shape

(4, 3)

In [106]:
#1D To 3D
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
ar_3d=ar1.reshape(2,3,2)
ar_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [108]:
ar_3d.ndim

3

In [109]:
#Iterating an array
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [110]:
for i in ar1:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [111]:
ar_n1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
for x in ar_n1:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [113]:
for i in ar_n1:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [114]:
ar_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [115]:
ar_3d.ndim

3

In [116]:
for x in ar_3d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [117]:
#join array
a11=np.array([1,2,3])
a22=np.array([3,4,5])

In [118]:
a=np.concatenate((a11,a22))
a

array([1, 2, 3, 3, 4, 5])

In [119]:
a2=np.stack((a11,a22),axis=1)# so axis=1 its row-wise
a2

array([[1, 3],
       [2, 4],
       [3, 5]])

In [120]:
a3=np.stack((a11,a22),axis=0)#column n-wise
a3

array([[1, 2, 3],
       [3, 4, 5]])

In [121]:
a4=np.hstack((a11,a22))#column wise joining
a4

array([1, 2, 3, 3, 4, 5])

In [122]:
a4=np.vstack((a11,a22))#row-wise joining
a4

array([[1, 2, 3],
       [3, 4, 5]])

In [123]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [124]:
a5=np.array_split(ar1,4)
a5

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [125]:
a2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
a2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [126]:
a2n=np.array_split(a2d,3,axis=1)

In [127]:
a2n

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [128]:
a2n2=np.hsplit(a2d,3)
a2n2

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [129]:
#array search:where()
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [130]:
x=np.where(ar1==10)
print(x)

(array([9], dtype=int64),)


In [131]:
x1=np.where(ar1%2==0)#even number
print(x1)

(array([ 1,  3,  5,  7,  9, 11], dtype=int64),)


In [132]:
x2=np.where(ar1%2==1)#odd number
print(x2)

(array([ 0,  2,  4,  6,  8, 10], dtype=int64),)


In [133]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [134]:
#sort array
z=np.array([1,4,7,2,3])
print(np.sort(z))

[1 2 3 4 7]


In [135]:
z=np.array([1,4,7,2,3])#desending array
print(np.sort(z)[::-1])

[7 4 3 2 1]


In [136]:
#Filtering Of Array
# Q array >22
s=np.array([21,22,23,24])
l=[]
for i in s:
    if i>22:
        l.append(True)
    else:
        l.append(False)
s_new=s[l]
print(s_new)
print(l)

[23 24]
[False, False, True, True]


In [137]:
#accept the 
n=np.array([1,2,3,4,5,6,7,8,9,10])
l=[]
for i in n:
    if i%2==0:
        l.append(True)
    else:
        l.append(False)
n_new=n[l]
print(n_new)
print(l)
        

[ 2  4  6  8 10]
[False, True, False, True, False, True, False, True, False, True]


In [138]:
#Random Module: rand function lise between 0 to 1 only   
import numpy as np
from numpy import random

In [139]:
x=random.randint(10)
x

7

In [140]:
x1=random.rand()#0 to 1 float number
x1

0.30922306990302695

In [141]:
x2=random.randint(10,size=(5))
x2

array([1, 7, 1, 6, 3])

In [142]:
x3=random.randint(20,size=(3,5))
x3

array([[16,  9,  1, 16, 13],
       [ 8, 13,  4, 13,  0],
       [ 7, 17, 16, 15,  7]])

In [143]:
x4=random.rand(5)#1-d array with values from 0 to 1
x4

array([0.85171958, 0.99962091, 0.73863772, 0.5755391 , 0.34117498])

In [144]:
x5=random.rand(3,4)
x5

array([[0.63833309, 0.88418018, 0.70471523, 0.26108753],
       [0.2662814 , 0.60937978, 0.74471139, 0.72596955],
       [0.02112357, 0.49874607, 0.5870338 , 0.38340213]])

In [145]:
#WAP to sort an array
N=np.array([1,6,7,8,11,15,2,30,25])
print(np.sort(N))

[ 1  2  6  7  8 11 15 25 30]


In [148]:
#WAP to accept 2 array from user and join them
ar1=input("Enter the Numbers of the first array, separated by spaces: ").split()
ar2=input("Enter the Numbers of the second array, separated by spaces: ").split()
result=ar1+ar2
print("concatenate Array:", result)

Enter the Numbers of the first array, separated by spaces: 1 2 3 
Enter the Numbers of the second array, separated by spaces: 3 4 5
concatenate Array: ['1', '2', '3', '3', '4', '5']


In [147]:
a1=np.array([3,7,8])
a2=np.array([3,4,5])
a=np.concatenate((a1,a2))
a

array([3, 7, 8, 3, 4, 5])