In [1]:
#Types of Libraries:
    #1. Keras = Machine learning/Data mining(regression,clustering,etc)
    #2. Matplotlib = Desigining charts,graphs,picharts,scatter plots,histogram,etc
    #3. Numpy = Array representation (assoiciated with various libraries internally)
    #4. NLTK = Natural language processing
    #5. OpenCV = Open source computer vision library (Specially for Image processing)
    #6. Pandas = Data analaysis (Features- Re-indexing, sorting, Iterative, concatination,etc.)........imp
    #7. PyTorch = Machine learning/ Deep learning
    #8. Scikit Learn =  Machine Learning
    #9. SciPy = Scientific Python( Statistics, Algebra, Integration math related functions)
    #10. Seaborn = Data Visualization library( High level interactive and informative pacakage)
    #11. Tensor Flow = Machine Learning Library( To compute tensor operations i.e. represent data in n-dimension matrices)

# Numpy

In [2]:
import numpy  as np

In [3]:
l1=[1,43,33,44]
a1=np.array(l1)
a1

array([ 1, 43, 33, 44])

In [4]:
t1=(2,3,4,5)
a2=np.array(t1)
a2

array([2, 3, 4, 5])

In [5]:
type(a2)

numpy.ndarray

In [6]:
a2.ndim

1

In [7]:
b1=np.array([[1,2,4],[5,7,7]])
b1


array([[1, 2, 4],
       [5, 7, 7]])

In [8]:
b1.ndim

2

In [9]:
c1=np.array([[[1,2,3],[4,5,6]],[[11,22,33],[78,69,55]],[[111,222,333],[77,55,44]]])
c1

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 11,  22,  33],
        [ 78,  69,  55]],

       [[111, 222, 333],
        [ 77,  55,  44]]])

In [10]:
#c1[0,:2,:2]
c1[0,0:,:2]

array([[1, 2],
       [4, 5]])

In [11]:
c1[2,0:,1:]

array([[222, 333],
       [ 55,  44]])

In [12]:
c1[1,0:,:2]

array([[11, 22],
       [78, 69]])

In [13]:
c1[1,0,1]

22

In [14]:
c1[2,1,0]

77

In [15]:
c1[2,0,2]

333

In [16]:
#Array with Numerical Ranges=arange(),linspace(),logspace()
#start,stop,dtype
import numpy as np

In [17]:
a1=np.arange(0,10,4,dtype="int")#0=start 10=stop 4 difference
a1

array([0, 4, 8])

In [18]:
a2=np.arange(0,10,4,dtype="float")#0=start 10=stop 4 difference
a2

array([0., 4., 8.])

In [19]:
a3=np.arange(0,50,5,dtype="int")#0=start 10=stop 5=difference
a3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
a4=np.linspace(0,10,5,endpoint=True,retstep=True)
a4        #5=num of iteration,endpoint=to add last element or not,retstep=returns difference

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

In [21]:
a5=np.linspace(0,10) #by default it takes 50 values
a5

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [22]:
a4=np.logspace(0,10,num=4,endpoint=False) #num=num of iteration,endpoint=to add last element or not
a4

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07])

In [23]:
a44=np.logspace(0,10,num=4,endpoint=False,base=2) #log(base 2)
a44

array([  1.        ,   5.65685425,  32.        , 181.01933598])

In [24]:
a45=np.logspace(0,10) #by default it takes 50 values
a45

array([1.00000000e+00, 1.59985872e+00, 2.55954792e+00, 4.09491506e+00,
       6.55128557e+00, 1.04811313e+01, 1.67683294e+01, 2.68269580e+01,
       4.29193426e+01, 6.86648845e+01, 1.09854114e+02, 1.75751062e+02,
       2.81176870e+02, 4.49843267e+02, 7.19685673e+02, 1.15139540e+03,
       1.84206997e+03, 2.94705170e+03, 4.71486636e+03, 7.54312006e+03,
       1.20679264e+04, 1.93069773e+04, 3.08884360e+04, 4.94171336e+04,
       7.90604321e+04, 1.26485522e+05, 2.02358965e+05, 3.23745754e+05,
       5.17947468e+05, 8.28642773e+05, 1.32571137e+06, 2.12095089e+06,
       3.39322177e+06, 5.42867544e+06, 8.68511374e+06, 1.38949549e+07,
       2.22299648e+07, 3.55648031e+07, 5.68986603e+07, 9.10298178e+07,
       1.45634848e+08, 2.32995181e+08, 3.72759372e+08, 5.96362332e+08,
       9.54095476e+08, 1.52641797e+09, 2.44205309e+09, 3.90693994e+09,
       6.25055193e+09, 1.00000000e+10])

In [25]:
#Reshaping of Array
v=np.array([10,20,30])
v.shape

(3,)

In [26]:
v1=np.array([10,20,50,40,90,89])
v1.shape

(6,)

In [27]:
np.reshape(v1,(3,2))

array([[10, 20],
       [50, 40],
       [90, 89]])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((2,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones((2,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
#Arithmatic function
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [37]:
np.add(a,b)

array([[ 12,  24,  36],
       [ 48,  60,  72],
       [ 84,  96, 108]])

In [38]:
c1=np.array([10,20,30])
c1

array([10, 20, 30])

In [39]:
np.add(a,c1)

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [40]:
np.subtract(a,b)

array([[-10, -20, -30],
       [-40, -50, -60],
       [-70, -80, -90]])

In [41]:
np.multiply(a,b)

array([[ 11,  44,  99],
       [176, 275, 396],
       [539, 704, 891]])

In [42]:
np.multiply(a,c1)

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

In [43]:
np.divide(a,b)

array([[0.09090909, 0.09090909, 0.09090909],
       [0.09090909, 0.09090909, 0.09090909],
       [0.09090909, 0.09090909, 0.09090909]])

In [44]:
np.divide(b,a)

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [45]:
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [46]:
np.power(a,b)

array([[          1,     4194304, -1504003197],
       [          0,  -146682003,           0],
       [-1031769369,           0,  -635723303]], dtype=int32)

In [47]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [48]:
np.power(b,a)

array([[         11,         484,       35937],
       [    3748096,   503284375,  1049571392],
       [-1769518299,  1627389952, -1200325565]], dtype=int32)

In [49]:
np.mod(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [50]:
np.mod(b,a) #b>a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

# Pandas

In [51]:
#Used for data Analysis
#Supports 3 data structures
#1. Series
#2. Dataframe
#3. Panel

# Series

In [52]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [53]:
l=[111,22,33,77,89]
l1=pd.Series(l)
l1

0    111
1     22
2     33
3     77
4     89
dtype: int64

In [54]:
type(l1)

pandas.core.series.Series

In [55]:
pd.Series(l,index=["a","b","c","d","e"])

a    111
b     22
c     33
d     77
e     89
dtype: int64

In [56]:
s=pd.Series()
s

Series([], dtype: float64)

In [57]:
#array to series
a=np.array([11,22,33])
a1=pd.Series(a)
a1

0    11
1    22
2    33
dtype: int32

In [58]:
type(a1)

pandas.core.series.Series

In [59]:
#Dictionary to series
d1={"a":10,"b":20,"c":40,"d":90}
d1

{'a': 10, 'b': 20, 'c': 40, 'd': 90}

In [60]:
d2=pd.Series(d1)
d2

a    10
b    20
c    40
d    90
dtype: int64

In [61]:
type(d2)

pandas.core.series.Series

# DataFrame

In [62]:
#excel
#csv
#dictionary
#list of tuple

In [63]:
c={"Name":["abc","def","ghi"],"perc":[90,40,50],"branch":["CS","IT","Comp"]}
c1=pd.DataFrame(c)
c1

Name  perc branch
0  abc    90     CS
1  def    40     IT
2  ghi    50   Comp

In [64]:
c

{'Name': ['abc', 'def', 'ghi'],
 'perc': [90, 40, 50],
 'branch': ['CS', 'IT', 'Comp']}

In [65]:
type(c1)

pandas.core.frame.DataFrame

In [66]:
s1=[("a",10),("b",40),("v",90)]
s1

[('a', 10), ('b', 40), ('v', 90)]

In [67]:
s2=pd.DataFrame(s1)   #Using List of tuple
s2

0   1
0  a  10
1  b  40
2  v  90

In [68]:
data=pd.read_excel(r"C:\Users\Admin\Documents\GitHub\edu-python\sample 1.xls")
data

0 First Name   Last Name  Gender        Country  Age        Date    Id
0    1      Dulce       Abril  Female  United States   32  15/10/2017  1562
1    2       Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
2    3     Philip        Gent    Male         France   36  21/05/2015  2587
3    4   Kathleen      Hanner  Female  United States   25  15/10/2017  3549
4    5    Nereida     Magwood  Female  United States   58  16/08/2016  2468
5    6     Gaston       Brumm    Male  United States   24  21/05/2015  2554
6    7       Etta        Hurn  Female  Great Britain   56  15/10/2017  3598
7    8    Earlean      Melgar  Female  United States   27  16/08/2016  2456
8    9   Vincenza     Weiland  Female  United States   40  21/05/2015  6548
9   10     Fallon     Winward  Female  Great Britain   28  16/08/2016  5486
10  11    Arcelia      Bouska  Female  Great Britain   39  21/05/2015  1258
11  12   Franklyn      Unknow    Male         France   38  15/10/2017  2579
12  13    Sherron    Ascencio  Female  Great Britain   32  16/08/2016  3256
13  14     Marcel   Zabriskie    Male  Great Britain   26  21/05/2015  2587
14  15       Kina    Hazelton  Female  Great Britain   31  16/08/2016  3259
15  16   Shavonne         Pia  Female         France   24  21/05/2015  1546
16  17     Shavon      Benito  Female         France   39  15/10/2017  3579
17  18   Lauralee     Perrine  Female  Great Britain   28  16/08/2016  6597
18  19     Loreta      Curren  Female         France   26  21/05/2015  9654
19  20     Teresa      Strawn  Female         France   46  21/05/2015  3569
20  21    Belinda     Partain  Female  United States   37  15/10/2017  2564
21  22      Holly        Eudy  Female  United States   52  16/08/2016  8561
22  23       Many      Cuccia  Female  Great Britain   46  21/05/2015  5489
23  24     Libbie       Dalby  Female         France   42  21/05/2015  5489
24  25     Lester     Prothro    Male         France   21  15/10/2017  6574
25  26     Marvel        Hail  Female  Great Britain   28  16/08/2016  5555
26  27    Angelyn        Vong  Female  United States   29  21/05/2015  6125
27  28  Francesca   Beaudreau  Female         France   23  15/10/2017  5412
28  29      Garth       Gangi    Male  United States   41  16/08/2016  3256
29  30      Carla    Trumbull  Female  Great Britain   28  21/05/2015  3264
30  31       Veta       Muntz  Female  Great Britain   37  15/10/2017  4569
31  32     Stasia      Becker  Female  Great Britain   34  16/08/2016  7521
32  33       Jona     Grindle  Female  Great Britain   26  21/05/2015  6458
33  34      Judie    Claywell  Female         France   35  16/08/2016  7569
34  35     Dewitt      Borger    Male  United States   36  21/05/2015  8514
35  36       Nena      Hacker  Female  United States   29  15/10/2017  8563
36  37     Kelsie     Wachtel  Female         France   27  16/08/2016  8642
37  38        Sau        Pfau  Female  United States   25  21/05/2015  9536
38  39    Shanice   Mccrystal  Female  United States   36  21/05/2015  2567
39  40      Chase      Karner    Male  United States   37  15/10/2017  2154
40  41     Tommie   Underdahl    Male  United States   26  16/08/2016  3265
41  42     Dorcas      Darity  Female  United States   37  21/05/2015  8765
42  43      Angel       Sanor    Male         France   24  15/10/2017  3259
43  44  Willodean        Harn  Female  United States   39  16/08/2016  3567
44  45     Weston     Martina    Male  United States   26  21/05/2015  6540
45  46       Roma  Lafollette  Female  United States   34  15/10/2017  2654
46  47     Felisa        Cail  Female  United States   28  16/08/2016  6525
47  48   Demetria       Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy        Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

In [69]:
data1=pd.read_csv(r"C:\Users\Admin\Documents\GitHub\edu-python\Credit_Risk_data.csv")
data1

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [70]:
data1.shape  #details in number of rows and columns in data frame

(614, 13)

In [71]:
data1.head() #used to display the first few rows 

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [72]:
data1.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [73]:
data1.tail()#by default last 5 rows

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [74]:
data1.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [75]:
data1.describe(include="all")

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP001002   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   
mean         NaN    NaN     NaN        NaN       NaN           NaN   
std          NaN    NaN     NaN        NaN       NaN           NaN   
min          NaN    NaN     NaN        NaN       NaN           NaN   
25%          NaN    NaN     NaN        NaN       NaN           NaN   
50%          NaN    NaN     NaN        NaN       NaN           NaN   
75%          NaN    NaN     NaN        NaN       NaN           NaN   
max          NaN    NaN     NaN        NaN       NaN           NaN   

        ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count        614.000000         614.000000  592.000000         600.00000   
unique              NaN                NaN         NaN               NaN   
top                 NaN                NaN         NaN               NaN   
freq                NaN                NaN         NaN               NaN   
mean        5403.459283        1621.245798  146.412162         342.00000   
std         6109.041673        2926.248369   85.587325          65.12041   
min          150.000000           0.000000    9.000000          12.00000   
25%         2877.500000           0.000000  100.000000         360.00000   
50%         3812.500000        1188.500000  128.000000         360.00000   
75%         5795.000000        2297.250000  168.000000         360.00000   
max        81000.000000       41667.000000  700.000000         480.00000   

        Credit_History Property_Area Loan_Status  
count       564.000000           614         614  
unique             NaN             3           2  
top                NaN     Semiurban           Y  
freq               NaN           233         422  
mean          0.842199           NaN         NaN  
std           0.364878           NaN         NaN  
min           0.000000           NaN         NaN  
25%           1.000000           NaN         NaN  
50%           1.000000           NaN         NaN  
75%           1.000000           NaN         NaN  
max           1.000000           NaN         NaN

In [76]:
data1["ApplicantIncome"].mean()

5403.459283387622

In [77]:
data1.ApplicantIncome.median()

3812.5

In [78]:
data1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [79]:
data1.ApplicantIncome

0      5849
1      4583
2      3000
3      2583
4      6000
       ... 
609    2900
610    4106
611    8072
612    7583
613    4583
Name: ApplicantIncome, Length: 614, dtype: int64

In [80]:
da_new=data1[data1.ApplicantIncome>4000]
da_new

Loan_ID  Gender Married Dependents Education Self_Employed  \
0    LP001002    Male      No          0  Graduate            No   
1    LP001003    Male     Yes          1  Graduate            No   
4    LP001008    Male      No          0  Graduate            No   
5    LP001011    Male     Yes          2  Graduate           Yes   
8    LP001018    Male     Yes          2  Graduate            No   
..        ...     ...     ...        ...       ...           ...   
604  LP002959  Female     Yes          1  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
8               4006             1526.0       168.0             360.0   
..               ...                ...         ...               ...   
604            12000                0.0       496.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
4               1.0         Urban           Y  
5               1.0         Urban           Y  
8               1.0         Urban           Y  
..              ...           ...         ...  
604             1.0     Semiurban           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[280 rows x 13 columns]

In [81]:
da_new.shape

(280, 13)

In [82]:
da_new1=data1[data1.ApplicantIncome<=4000]
da_new1

Loan_ID  Gender Married Dependents     Education Self_Employed  \
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes         3+      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
6               2333             1516.0        95.0             360.0   
7               3036             2504.0       158.0             360.0   
10              3200              700.0        70.0             360.0   
..               ...                ...         ...               ...   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   

     Credit_History Property_Area Loan_Status  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
6               1.0         Urban           Y  
7               0.0     Semiurban           N  
10              1.0         Urban           Y  
..              ...           ...         ...  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  

[334 rows x 13 columns]

In [83]:
da_new1.shape

(334, 13)

In [84]:
data1.shape

(614, 13)

In [85]:
da_n3=data1[(data1.Gender=="Male")&(data1.ApplicantIncome>4000)]
da_n3

Loan_ID Gender Married Dependents Education Self_Employed  \
0    LP001002   Male      No          0  Graduate            No   
1    LP001003   Male     Yes          1  Graduate            No   
4    LP001008   Male      No          0  Graduate            No   
5    LP001011   Male     Yes          2  Graduate           Yes   
8    LP001018   Male     Yes          2  Graduate            No   
..        ...    ...     ...        ...       ...           ...   
599  LP002948   Male     Yes          2  Graduate            No   
602  LP002953   Male     Yes         3+  Graduate            No   
610  LP002979   Male     Yes         3+  Graduate            No   
611  LP002983   Male     Yes          1  Graduate            No   
612  LP002984   Male     Yes          2  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
8               4006             1526.0       168.0             360.0   
..               ...                ...         ...               ...   
599             5780                0.0       192.0             360.0   
602             5703                0.0       128.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
4               1.0         Urban           Y  
5               1.0         Urban           Y  
8               1.0         Urban           Y  
..              ...           ...         ...  
599             1.0         Urban           Y  
602             1.0         Urban           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  

[229 rows x 13 columns]

In [86]:
#married male with greater than 4000
da_n4=data1[(data1.Gender=="Male")&(data1.Married=="Yes")&(data1.ApplicantIncome>4000)]
da_n4

Loan_ID Gender Married Dependents     Education Self_Employed  \
1    LP001003   Male     Yes          1      Graduate            No   
5    LP001011   Male     Yes          2      Graduate           Yes   
8    LP001018   Male     Yes          2      Graduate            No   
9    LP001020   Male     Yes          1      Graduate            No   
18   LP001038   Male     Yes          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
599  LP002948   Male     Yes          2      Graduate            No   
602  LP002953   Male     Yes         3+      Graduate            No   
610  LP002979   Male     Yes         3+      Graduate            No   
611  LP002983   Male     Yes          1      Graduate            No   
612  LP002984   Male     Yes          2      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
5               5417             4196.0       267.0             360.0   
8               4006             1526.0       168.0             360.0   
9              12841            10968.0       349.0             360.0   
18              4887                0.0       133.0             360.0   
..               ...                ...         ...               ...   
599             5780                0.0       192.0             360.0   
602             5703                0.0       128.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   

     Credit_History Property_Area Loan_Status  
1               1.0         Rural           N  
5               1.0         Urban           Y  
8               1.0         Urban           Y  
9               1.0     Semiurban           N  
18              1.0         Rural           N  
..              ...           ...         ...  
599             1.0         Urban           Y  
602             1.0         Urban           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  

[167 rows x 13 columns]

In [87]:
da_n4.shape

(167, 13)

In [88]:
#married female with graduate and income>2k
da_n5=data1[(data1.Gender=="Female")&(data1.Married=="Yes")&(data1.Education=="Graduate")&(data1.ApplicantIncome>2000)]
da_n5

Loan_ID  Gender Married Dependents Education Self_Employed  \
37   LP001112  Female     Yes          0  Graduate            No   
48   LP001146  Female     Yes          0  Graduate            No   
54   LP001186  Female     Yes          1  Graduate           Yes   
96   LP001327  Female     Yes          0  Graduate            No   
111  LP001387  Female     Yes          0  Graduate           NaN   
116  LP001404  Female     Yes          0  Graduate            No   
136  LP001489  Female     Yes          0  Graduate            No   
145  LP001514  Female     Yes          0  Graduate            No   
146  LP001516  Female     Yes          2  Graduate            No   
166  LP001577  Female     Yes          0  Graduate            No   
184  LP001639  Female     Yes          0  Graduate            No   
198  LP001671  Female     Yes          0  Graduate            No   
219  LP001734  Female     Yes          2  Graduate            No   
297  LP001954  Female     Yes          1  Graduate            No   
328  LP002086  Female     Yes          0  Graduate            No   
353  LP002142  Female     Yes          0  Graduate           Yes   
354  LP002143  Female     Yes          0  Graduate            No   
495  LP002586  Female     Yes          1  Graduate            No   
516  LP002670  Female     Yes          2  Graduate            No   
540  LP002741  Female     Yes          1  Graduate            No   
559  LP002804  Female     Yes          0  Graduate            No   
561  LP002813  Female     Yes          1  Graduate           Yes   
582  LP002894  Female     Yes          0  Graduate            No   
604  LP002959  Female     Yes          1  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
37              3667             1459.0       144.0             360.0   
48              2645             3440.0       120.0             360.0   
54             11500                0.0       286.0             360.0   
96              2484             2302.0       137.0             360.0   
111             2929             2333.0       139.0             360.0   
116             3167             2283.0       154.0             360.0   
136             4583                0.0        84.0             360.0   
145             2330             4486.0       100.0             360.0   
146            14866                0.0        70.0             360.0   
166             4583                0.0       112.0             360.0   
184             3625                0.0       108.0             360.0   
198             3416             2816.0       113.0             360.0   
219             4283             2383.0       127.0             360.0   
297             4666                0.0       135.0             360.0   
328             4333             2451.0       110.0             360.0   
353             5500                0.0       105.0             360.0   
354             2423              505.0       130.0             360.0   
495             3326              913.0       105.0              84.0   
516             2031             1632.0       113.0             480.0   
540             4608             2845.0       140.0             180.0   
559             4180             2306.0       182.0             360.0   
561            19484                0.0       600.0             360.0   
582             3166                0.0        36.0             360.0   
604            12000                0.0       496.0             360.0   

     Credit_History Property_Area Loan_Status  
37              1.0     Semiurban           Y  
48              0.0         Urban           N  
54              0.0         Urban           N  
96              1.0     Semiurban           Y  
111             1.0     Semiurban           Y  
116             1.0     Semiurban           Y  
136             1.0         Rural           N  
145             1.0     Semiurban           Y  
146             1.0         Urban           Y  

In [89]:
da_n5.shape

(24, 13)

In [90]:
data1.shape

(614, 13)

In [91]:
data1.groupby("Gender").ApplicantIncome.mean()

Gender
Female    4643.473214
Male      5446.460123
Name: ApplicantIncome, dtype: float64

In [92]:
data1.groupby("Married").ApplicantIncome.mean()

Married
No     4970.384977
Yes    5629.173367
Name: ApplicantIncome, dtype: float64

In [93]:
data1.groupby("Gender").agg(["count","min","max","mean","median"])

ApplicantIncome                                  CoapplicantIncome  \
                 count  min    max         mean  median             count   
Gender                                                                      
Female             112  210  19484  4643.473214  3583.0               112   
Male               489  150  81000  5446.460123  3865.0               489   

                                           ... Loan_Amount_Term               \
        min      max         mean  median  ...            count   min    max   
Gender                                     ...                                 
Female  0.0  41667.0  1108.008929     0.0  ...              109  36.0  480.0   
Male    0.0  33837.0  1742.932352  1430.0  ...              478  12.0  480.0   

                          Credit_History                             
              mean median          count  min  max      mean median  
Gender                                                               
Female  352.293578  360.0            101  0.0  1.0  0.831683    1.0  
Male    339.665272  360.0            451  0.0  1.0  0.847007    1.0  

[2 rows x 25 columns]

In [94]:
pd.crosstab(data1.Gender,data1.Loan_Status)

Loan_Status    N    Y
Gender               
Female        37   75
Male         150  339

In [95]:
pd.crosstab(data1.Gender,data1.Property_Area)

Property_Area  Rural  Semiurban  Urban
Gender                                
Female            24         55     33
Male             151        172    166

In [96]:
loan=data1["Loan_ID"]
loan

0      LP001002
1      LP001003
2      LP001005
3      LP001006
4      LP001008
         ...   
609    LP002978
610    LP002979
611    LP002983
612    LP002984
613    LP002990
Name: Loan_ID, Length: 614, dtype: object

In [97]:
data1=data1.drop(["Loan_ID"],axis=1)
data1

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 12 columns]

In [98]:
data1.shape

(614, 12)

# Cleaning the data(preprocessing)

In [99]:
data1.describe(include="all")

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
count     601     611        599       614           582       614.000000   
unique      2       2          4         2             2              NaN   
top      Male     Yes          0  Graduate            No              NaN   
freq      489     398        345       480           500              NaN   
mean      NaN     NaN        NaN       NaN           NaN      5403.459283   
std       NaN     NaN        NaN       NaN           NaN      6109.041673   
min       NaN     NaN        NaN       NaN           NaN       150.000000   
25%       NaN     NaN        NaN       NaN           NaN      2877.500000   
50%       NaN     NaN        NaN       NaN           NaN      3812.500000   
75%       NaN     NaN        NaN       NaN           NaN      5795.000000   
max       NaN     NaN        NaN       NaN           NaN     81000.000000   

        CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
count          614.000000  592.000000         600.00000      564.000000   
unique                NaN         NaN               NaN             NaN   
top                   NaN         NaN               NaN             NaN   
freq                  NaN         NaN               NaN             NaN   
mean          1621.245798  146.412162         342.00000        0.842199   
std           2926.248369   85.587325          65.12041        0.364878   
min              0.000000    9.000000          12.00000        0.000000   
25%              0.000000  100.000000         360.00000        1.000000   
50%           1188.500000  128.000000         360.00000        1.000000   
75%           2297.250000  168.000000         360.00000        1.000000   
max          41667.000000  700.000000         480.00000        1.000000   

       Property_Area Loan_Status  
count            614         614  
unique             3           2  
top        Semiurban           Y  
freq             233         422  
mean             NaN         NaN  
std              NaN         NaN  
min              NaN         NaN  
25%              NaN         NaN  
50%              NaN         NaN  
75%              NaN         NaN  
max              NaN         NaN

In [100]:
#to check missing values

In [101]:
data1.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [102]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             601 non-null    object 
 1   Married            611 non-null    object 
 2   Dependents         599 non-null    object 
 3   Education          614 non-null    object 
 4   Self_Employed      582 non-null    object 
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object 
 11  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB


In [103]:
#treatment to missing values :1. drop NA  2.Impute NA

In [104]:
#data1=data1.dropna()

In [105]:
data1.shape

(614, 12)

In [106]:
#Imputation
data1.Gender.value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [107]:
data1.Gender=data1.Gender.fillna("Female")

In [108]:
data1.Gender.value_counts()

Male      489
Female    125
Name: Gender, dtype: int64

In [109]:
data1.isnull().sum()

Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [110]:
data1.Married.value_counts()

Yes    398
No     213
Name: Married, dtype: int64

In [111]:
data1.Married=data1.Married.fillna('No')

In [112]:
data1.Married.value_counts()

Yes    398
No     216
Name: Married, dtype: int64

In [113]:
data1.isnull().sum()

Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [114]:
data1.Self_Employed.value_counts()

No     500
Yes     82
Name: Self_Employed, dtype: int64

In [115]:
data1.Self_Employed=data1.Self_Employed.fillna("Yes")

In [116]:
data1.Self_Employed.value_counts()

No     500
Yes    114
Name: Self_Employed, dtype: int64

In [117]:
data1.isnull().sum()

Gender                0
Married               0
Dependents           15
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [118]:
data1.Dependents.value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [119]:
data1.Dependents=data1.Dependents.fillna("3+")

In [121]:
data1.Dependents.value_counts()

0     345
1     102
2     101
3+     66
Name: Dependents, dtype: int64

In [122]:
data1.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [125]:
data1.LoanAmount =data1.LoanAmount.fillna(data1.LoanAmount.mean())

In [126]:
data1.Loan_Amount_Term .value_counts()

360.0    512
180.0     44
480.0     15
300.0     13
240.0      4
84.0       4
120.0      3
60.0       2
36.0       2
12.0       1
Name: Loan_Amount_Term, dtype: int64

In [128]:
data1.Loan_Amount_Term=data1.Loan_Amount_Term.fillna(data1.Loan_Amount_Term.median())

In [129]:
data1.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [130]:
data1.Credit_History.value_counts()

1.0    475
0.0     89
Name: Credit_History, dtype: int64

In [131]:
data1.Credit_History=data1.Credit_History.fillna(0.0)

In [133]:
data1.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [135]:
#data1.info()